// shortCode ✴ biblispec 2026
const shortCode={
			"mushroom": "🍄", "anchor": "⚓", "wintertree": "🪾",
			"telephone": "☎️","television": "📺","radio": "📻","laptop": "💻","desktop": "🖥️", "satellite": "🛰️",
			"pager": "📟","fax": "📠","printer": "🖨️","keyboard": "⌨️","mouse": "🖱️", "station": "📡",
			"floppy_disk": "💾","computer_disk": "💽","optical_disc": "💿","video_camera": "📹","video_cassette": "📼",
			"goose":"🪿","jellyfish":"🪼","lime":"🫒","family":"👨‍👩‍👧‍👦", "cat":"🐱","dog":"🐶","moose":"🫎","donkey":"🫏",
			"pizza":"🍕","beer":"🍺","coffee":"☕","cake":"🎂", "beans":"🫘","jar":"🫙",
			"maracas":"🪇","flute":"🪈","keys":"🎹","guitar":"🎸","drum":"🥁","microphone":"🎤","saxophone":"🎷","trumpet":"🎺","violin":"🎻",
			"headphones":"🎧","score":"🎼","music":"🎵","phone":"📱","computer":"💻","book":"📖","money":"💵",
			"plunger":"🪠","robot":"🤖","unicorn":"🦄","thumbsup":"👍","fire":"🔥","star":"⭐","eyes":"👀",
			"trophy":"🏆","skull":"💀","clap":"👏","100":"💯",
			"heart":"❤️","black_heart":"🖤","white_heart":"🤍","pink_heart":"🩷","light_blue_heart":"🩵","grey_heart":"🩶","sparkling_heart":"💖","broken_heart":"💔",
			"warning":"⚠️","question":"❓","exclamation":"❗",
			"zzz":"💤","clock":"⏰","hourglass":"⏳",
			"lightning":"⚡","rainbow":"🌈","moon":"🌙","sun":"☀️",
			"cloud":"☁️","umbrella":"☔","snowman":"⛄",
			"gift":"🎁","balloon":"🎈","rocket":"🚀",
			"car":"🚗","plane":"✈️","bike":"🚲",
			"football":"⚽","basketball":"🏀","tennis":"🎾","medal":"🏅",
			"thinking":"🤔","cool":"😎","blush":"😊","sleepy":"😴","heart_eyes":"😍","eyes_wide":"😳","clown":"🤡","cowboy":"🤠",
			"grinning":"😀","smiley":"😃","smile":"😄","grin":"😁","laughing":"😆","sweat_smile":"😅","rofl":"🤣","joy":"😂","melting_face":"🫠",
			"face_with_peeking_eye":"🫢","saluting_face":"🫡","dotted_line_face":"🫥","face_with_diagonal_mouth":"🫣",
			"pregnant_person":"🫄","person_with_crown":"🫅","people_hugging":"🫂",
			"fingers_crossed":"🫰","rightwards_pushing_hand":"🫷","leftwards_pushing_hand":"🫸","palm_down_hand":"🫳","palm_up_hand":"🫴","pointing_finger":"🫵",
			"nest_with_eggs":"🪺","empty_nest":"🪹",
			"hook":"🪝","low_battery":"🪫","crutch":"🩼","shaking_face":"🫨",
			"khanda":"🪯","wireless":"🛜","phoenix":"🪶","broken_chain":"⛓️‍💥","ginger_root":"🫚",
			"hair_pick":"🪮","folding_hand_fan":"🪭","pea_pod":"🫛","hyacinth":"🪻",
			"shovel":"🫷","troll":"🧌","wing":"🪽","pouring_liquid":"🫗",
			"fish":"🐟","ballot":"☑","check":"✅","cross":"❎"
};
