


/*

{
	"name": "MOS Technology 6502",
	"version": "1.4.0",
	"description": "8 bit CPU",
	"copyright": "(C) 2026 Simon Armstrong",
	"credit": "Curated by Simon Armstrong with help from VIC-20 reference manual and ChatGPT",
	"license":{"name": "MIT", "url": "https://opensource.org/licenses/MIT"},
	"repository":{"type": "git", "url": "https://github.com/nitrologic/biblispec"},
	"addressmode":[
		"immediate",
		"zeropage",
		"zeropage,X",
		"absolute",
		"absolute,X",
		"absolute,Y",
		"(indirect,X)",
		"(indirect),Y"
	],
	"instruction":{  
		"ADC":{"opcodes":"69 65 75 6D 7D 79 61 71","flags":"NZCV","label":"ADD MEMORY TO ACCUMULATOR WITH CARRY","spec":0},
		"AND":{"opcodes":"29 25 35 2D 3D 39 21 31","flags":"NZ","label":"LOGICAL AND WITH ACCUMULATOR","spec":15},
		"ASL":{"opcodes":"0A 06 16 0E 1E","flags":"NZC","label":"SHIFT LEFT ONE BIT","spec":12},
		"BCC":{"opcodes":"90","flags":"","label":"BRANCH IF CARRY CLEAR","spec":5},
		"BCS":{"opcodes":"B0","flags":"","label":"BRANCH IF CARRY SET","spec":5},
		"BEQ":{"opcodes":"F0","flags":"","label":"BRANCH IF RESULT ZERO","spec":5},
		"BIT":{"opcodes":"24 2C","flags":"NZV","label":"TEST BITS IN MEMORY WITH ACCUMULATOR","spec":7},
		"BMI":{"opcodes":"30","flags":"","label":"BRANCH IF MINUS","spec":5},
		"BNE":{"opcodes":"D0","flags":"","label":"BRANCH IF RESULT NOT ZERO","spec":5},
		"BPL":{"opcodes":"10","flags":"","label":"BRANCH IF PLUS","spec":5},
		"BRK":{"opcodes":"00","flags":"","label":"FORCE INTERRUPT","spec":4},
		"BVC":{"opcodes":"50","flags":"","label":"BRANCH IF OVERFLOW CLEAR","spec":5},
		"BVS":{"opcodes":"70","flags":"","label":"BRANCH IF OVERFLOW SET","spec":5},
		"CLC":{"opcodes":"18","flags":"","label":"CLEAR CARRY FLAG","spec":0},
		"CLD":{"opcodes":"D8","flags":"","label":"CLEAR DECIMAL MODE","spec":0},
		"CLI":{"opcodes":"58","flags":"","label":"CLEAR INTERRUPT DISABLE","spec":0},
		"CLV":{"opcodes":"B8","flags":"","label":"CLEAR OVERFLOW FLAG","spec":0},
		"CMP":{"opcodes":"C9 C5 D5 CD DD D9 C1 D1","flags":"NZC","label":"COMPARE MEMORY WITH ACCUMULATOR","spec":15},
		"CPX":{"opcodes":"E0 E4 EC","flags":"NZC","label":"COMPARE MEMORY WITH X REGISTER","spec":9},
		"CPY":{"opcodes":"C0 C4 CC","flags":"NZC","label":"COMPARE MEMORY WITH Y REGISTER","spec":9},	
		"DEC":{"opcodes":"C6 D6 CE DE","flags":"NZ","label":"DECREMENT MEMORY","spec":11},
		"DEX":{"opcodes":"CA","flags":"NZ","label":"DECREMENT X REGISTER","spec":0},
		"DEY":{"opcodes":"88","flags":"NZ","label":"DECREMENT Y REGISTER","spec":0},
		"EOR":{"opcodes":"49 45 55 4D 5D 59 41 51","flags":"NZ","label":"EXCLUSIVE OR WITH ACCUMULATOR","spec":15},
		"INC":{"opcodes":"E6 F6 EE FE","flags":"NZ","label":"INCREMENT MEMORY","spec":11},
		"INX":{"opcodes":"E8","flags":"NZ","label":"INCREMENT X REGISTER","spec":0},
		"INY":{"opcodes":"C8","flags":"NZ","label":"INCREMENT Y REGISTER","spec":0},
		"JSR":{"opcodes":"20","flags":"","label":"JUMP TO SUBROUTINE","spec":6},
		"JMP":{"opcodes":"4C 6C","flags":"","label":"JUMP TO NEW LOCATION","spec":8},
		"LDA":{"opcodes":"A9 A5 B5 AD BD B9 A1 B1","flags":"NZ","label":"LOAD ACCUMULATOR WITH MEMORY","spec":15},
		"LDX":{"opcodes":"A2 A6 B6 AE BE","flags":"NZ","label":"LOAD X REGISTER WITH MEMORY","spec":13},
		"LDY":{"opcodes":"A0 A4 B4 AC BC","flags":"NZ","label":"LOAD Y REGISTER WITH MEMORY","spec":13},
		"LSR":{"opcodes":"4A 46 56 4E 5E","flags":"NZC","label":"SHIFT RIGHT ONE BIT","spec":12},
		"NOP":{"opcodes":"EA","flags":"","label":"NO OPERATION","spec":0},
		"ORA":{"opcodes":"09 05 15 0D 1D 19 01 11","flags":"NZ","label":"LOGICAL OR WITH ACCUMULATOR","spec":15},
		"PHA":{"opcodes":"48","flags":"","label":"PUSH ACCUMULATOR ON STACK","spec":1},
		"PHP":{"opcodes":"08","flags":"","label":"PUSH PROCESSOR STATUS ON STACK","spec":1},
		"PLA":{"opcodes":"68","flags":"NZ","label":"PULL ACCUMULATOR FROM STACK","spec":2},
		"PLP":{"opcodes":"28","flags":"NZCIDV","label":"PULL PROCESSOR STATUS FROM STACK","spec":2},
		"ROL":{"opcodes":"2A 26 36 2E 3E","flags":"NZC","label":"ROTATE ONE BIT LEFT","spec":12},
		"ROR":{"opcodes":"6A 66 76 6E 7E","flags":"NZC","label":"ROTATE ONE BIT RIGHT","spec":12},
		"RTI":{"opcodes":"40","flags":"NZCIDV","label":"RETURN FROM INTERRUPT","spec":3},
		"RTS":{"opcodes":"60","flags":"","label":"RETURN FROM SUBROUTINE","spec":3},
		"SBC":{"opcodes":"E9 E5 F5 ED FD F9 E1 F1","flags":"NZCV","label":"SUBTRACT MEMORY FROM ACCUMULATOR WITH BORROW","spec":15},
		"SEC":{"opcodes":"38","flags":"C","label":"SET CARRY FLAG","spec":0},
		"SED":{"opcodes":"F8","flags":"D","label":"SET DECIMAL MODE","spec":0},
		"SEI":{"opcodes":"78","flags":"I","label":"SET INTERRUPT DISABLE","spec":0},
		"STA":{"opcodes":"85 95 8D 9D 99 81 91","flags":"","label":"STORE ACCUMULATOR IN MEMORY","spec":14},
		"STX":{"opcodes":"86 96 8E","flags":"","label":"STORE X REGISTER IN MEMORY","spec":10},
		"STY":{"opcodes":"84 94 8C","flags":"","label":"STORE Y REGISTER IN MEMORY","spec":10},
		"TAX":{"opcodes":"AA","flags":"NZ","label":"TRANSFER ACCUMULATOR TO X","spec":0},
		"TAY":{"opcodes":"A8","flags":"NZ","label":"TRANSFER ACCUMULATOR TO Y","spec":0},
		"TSX":{"opcodes":"BA","flags":"NZ","label":"TRANSFER STACK POINTER TO X","spec":0},
		"TXA":{"opcodes":"8A","flags":"NZ","label":"TRANSFER X TO ACCUMULATOR","spec":0},
		"TXS":{"opcodes":"9A","flags":"","label":"TRANSFER X TO STACK POINTER","spec":0},
		"TYA":{"opcodes":"98","flags":"NZ","label":"TRANSFER Y TO ACCUMULATOR","spec":0}
	},
	"profile":[
		{"bytes":[1],"cycles":[2]},
		{"bytes":[1],"cycles":[3]},
		{"bytes":[1],"cycles":[4]},
		{"bytes":[1],"cycles":[6]},
		{"bytes":[1],"cycles":[7]},
		{"bytes":[2],"cycles":[2]},
		{"bytes":[3],"cycles":[6]},
		{"bytes":[2,3],"cycles":[3,4]},
		{"bytes":[3,3],"cycles":[3,5]},
		{"bytes":[2,2,3],"cycles":[2,3,4]},
		{"bytes":[2,2,3],"cycles":[3,4,4]},
		{"bytes":[2,2,3,3],"cycles":[5,6,6,7]},
		{"bytes":[1,2,2,3,3],"cycles":[2,5,6,6,7]},
		{"bytes":[2,2,2,3,3],"cycles":[2,3,4,4,4]},
		{"bytes":[2,2,3,3,3,2,2],"cycles":[3,4,4,5,5,6,6]},
		{"bytes":[2,2,2,3,3,3,2,2],"cycles":[2,3,4,4,4,4,6,5]}
	],
	"interrupts":{
		"IRQ":{"pin":4,"address":"FFFE"},
		"RESET":{"pin":40,"address":"FFFC"},
		"NMI":{"pin":6,"address":"FFFA"}
	}
}

*/